name: zenit_ui
description: ZenitUI library.
version: 0.0.10
homepage: dahliaos.io
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^2.0.1
  handy_window: ^0.3.1

dev_dependencies:
  lint: ^2.1.2
